# Your variable
# shell scripting
YOUR_VARIABLE1 = 25
YOUR_VARIABLE2 = "HI"



all: main

main: linked_list.cpp main.cpp
	g++ linked_list.cpp main.cpp -std=c++17 -o main

# usage: make linked_list
# linked_list.o: linked_list.cpp
# 	g++ -std=c++17 -c linked_list.cpp

# main.o: main.cpp
# 	g++ -std=c++17 -c main.cpp

say_hi:
	echo "Hi"